### ISSUE TITLE
## 2. 주제 선정 및 주요 기능 

### ISSUE THREAD

**Issue by Euiseon-Lee** [Euiseon-Lee/KH1_FINAL#2]
## 경매나라

<br>

**< 경매나라 Overview >**

1.  지역 기반의 경매 시스템
2.  직거래 기반으로 운영됨
3.  참고사이트:	
		1) 당근마켓 (APP) 
		2) 야후옥션 https://page.auctions.yahoo.co.jp/jp/auction/d1053085466
		3) 이베이 https://www.ebay.com/itm/144564110598?hash=item21a8b14506:g:a4gAAOSwLwdiiKGr

<br>

**<기능 측면>**
1. 회원시스템
	- 통합으로 운영 (판매자+구매자)
	- 휴대폰번호(unique)

2. 경매시스템
	1) 경매형태
		1) 경매시작: 최초 입찰가 이상 입찰할 때 경매가 시작됨
		2) 즉시구매: 최고 입찰가에 도달한 경우 즉시구매가 가능 (경매는 즉시 종료)
	2) 경매등록
		구매자가 경매할 물품을 올리면 경매 시작이 가능해진다
			= DB에서 데이터 insert
	3) 경매수정
		입찰가가 DB에 입력되면 수정불가, 그 전까지는 허용 
			= DB에서 데이터의 status 컬럼 update
	4) 경매취소
		입찰한 고객이 없을 시 경매취소 가능, 불이익 없음
			= DB에서 데이터의 status 컬럼 update
	5) 경매중지
		입찰이 시작된 이후 취소하는 경우
		특정 기간 동안 몇 회 이상 판매중지 시 불이익을 주는 기준이 됨
		상세페이지에서 경매중지상품으로 고지한다 
			= DB에서 데이터의 status 컬럼 update	
	6) ★경매참여
		1. 참여할 때부터 포인트를 소모?
		2. 참여할땐 포인트 소모 없이 가격만 제시?
	7) ★경매종료
		1. 최종 입찰 시 입찰되지 않은 참여자의 포인트 복구?
		2. 최종 입찰시에만 해당 구매자의 포인트가 소모되게 구현?

3. 결제시스템
	- 포인트제도로 운영
	- 수수료 5% -> 최종 낙찰가 기준으로 적용하며 판매자 부담
	- 포인트가 있는 상태에서는 바로 입찰
	- 포인트가 없으면 포인트 충전 창으로 이동한다
	- 포인트 충전은 API 사용
	- 포인트 (일부) 사용 시 취소 불가 (청약철회 7일)
	- 출금은 포인트 차감으로 구현 (출금했다 치고 테이블에서 제거한다) 

5. 채팅시스템
	- 입찰 전까지는 익명으로 채팅
	- 입찰 이후에는 닉네임으로 채팅 
	- 알림기능은 강사님께 여쭤보자

<br>

**<화면 측면>**
1. 회원 관련	
	1) 회원가입 페이지
		- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간 기재하도록 한다
		- 주소 API (동 기준) => 시, 구, 동 기준으로 조회하는 용도

	2) 마이페이지 페이지
		-  회원정보 수정 페이지
			- 프로필사진 -> 등록, 수정, 삭제
			- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간
			- 거래후기(한줄평 <- 해당 판매자와 거래한 회원만 작성할 수 있다)
			- 경매중지횟수
			- 과거경매이력
				- 판매
				- 구매
		- 탈퇴 페이지

2. 관리자 관련
	- 블랙관리 페이지
	- 허위상품관리 페이지
	- 고객센터(이메일기재 - 추후 고민)
	- 경매목록 카테고리 추가/삭제 페이지

3. 경매 관련
	1) 경매목록 페이지
		- 카테고리로 분류 (대분류)
		- 시, 구, 동 선택가능한 탭 필요
		- 검색: 카테고리 / 제목 + 내용검색
		- 경매 등록

	2) 경매상세 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 판매자 닉네임 + 프로필 => 누르면 마이페이지로 이동 OR 모달창 띄우기
		- 현재입찰가, 기간, 남은 시간
		- 경매입찰가 넣을 수 있는 입력창
		- 채팅버튼

	3) 경매등록 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 경매 시작가격, 즉시구매 가격
		- 경매 기간 == 경매 종료 날짜 및 시간 (경매는 등록 즉시 개시)	

4. 결제 관련
	1) 포인트사용: 입찰금액보다 포인트가 더 많은 경우
		- 입찰이 자동으로 진행 (따로 페이지 구현하지 않음)

	2) 포인트 충전 페이지: 입찰금액보다 포인트가 더 적은 경우
		- 충전금액?
		- API

	3) 포인트차감(출금) 페이지
		- 은행계좌 받고 버튼 누르면 완료

6. 채팅 관련
	- 화면관련은 미정

**Comment by Euiseon-Lee** [comment]
Q. 회원등급은?
       -> 따로 구분하지 않되 거래성사가 많이 된 판매자에게 물건 정렬 시 혜택 제공

Q. 많이 이용한 고객에 대한 메리트는 없는지?
       -> 별도의 메리트를 제공하지 않으나 회사 측에서 허위매물, 경매중지 등의 변수를 철저히 모니터링함으로써 거래의 신뢰도를 높여 "믿고 사용할 수 있는 사이트"가 되도록 한다 (고객이 메리트 없이도 사용할 수 있는 사이트를 구현하고자 한다)

Q. 포인트 충전 시 고액에 관한 할인? 
       -> 없다

**Comment by Euiseon-Lee** [comment]
### 22-06-03 금 회의내용

## 경매나라

<br>

**경매나라 Overview**
	1. 지역 기반의 경매 시스템
	2. 직거래 기반으로 운영됨
	3. 참고:	
> - 		당근마켓 (어플) 
> - 		야후옥션 https://page.auctions.yahoo.co.jp/jp/auction/d1053085466
> - 		이베이 https://www.ebay.com/itm/144564110598?hash=item21a8b14506:g:a4gAAOSwLwdiiKGr

<br>

**<기능 측면>**
1. 회원
	- 통합으로 운영 (판매자+구매자)
	- 휴대폰번호(unique)

2. 경매시스템
	- 경매형태
		1. 경매시작: 최초 입찰가 이상 입찰할 때 경매가 시작됨
		2. 즉시구매: 최고 입찰가에 도달한 경우 즉시구매가 가능 (경매는 즉시 종료)
	- 경매등록
		최대입찰/즉시구매 최고가 설정 = 1조 (14자리)
		입찰금액 기본단위 = (default)100 / 1000 / 10,000 / 100,000 / 1,000,000원 단위 
		구매자가 경매할 물품을 올리면 경매 시작이 가능해진다
			= DB에서 데이터 insert
	- 경매수정
		입찰가가 DB에 입력되면 수정불가, 그 전까지는 허용 
			= DB에서 데이터의 status 컬럼 update
	- 경매취소
		입찰한 고객이 없을 시 경매취소 가능, 불이익 없음
			= DB에서 데이터의 status 컬럼 update
	- 경매중지
		입찰이 시작된 이후 취소하는 경우
		특정 기간 동안 몇 회 이상 판매중지 시 불이익을 주는 기준이 됨
		상세페이지에서 경매중지상품으로 고지한다 
			= DB에서 데이터의 status 컬럼 update
		
	- 경매참여
		참여할땐 포인트 소모 없이 가격만 제시
	- 경매종료
		최종 입찰시에만 해당 구매자의 포인트가 소모되게 구현


3. 결제시스템
	- 포인트제도로 운영
	- 수수료 5% -> 최종 낙찰가 기준으로 적용하며 판매자 부담
	- 포인트가 있는 상태에서는 바로 입찰 (잔여포인트 보여주고 결제확인 버튼있는 페이지가 필요)
	- 포인트가 없으면 포인트 충전 창으로 이동한다
	- 포인트 충전은 API 사용
	- 포인트 (일부) 사용 시 취소 불가 (청약철회 7일)
	- [판매자] 출금은 포인트 차감으로 구현 (출금했다 치고 테이블에서 제거한다) 
	- [낙찰 완료시] 확인 메일 발송 + 결제링크 (포인트 충분한지 검사 => 이 결과에 따라 이동)
	- [결제 완료시] 확인 메일 발송
	- [거래 확정 버튼] 누르면 판매자에게 포인트가 전송되는 시스템 (중개료 빼고)
	- [거래 기간] ???일 ???주 안에 거래하지 않으면 거래 취소처리 => 판매자에게 불이익 (구매자에게 포인트 돌려줘야함)
	- [결제 유효기간] 24시간 기준, 구매자가 링크를 타고 결제하지 않는 경우 거래 취소처리 => 구매자에게 불이익
			이 경우 거래는 전체 파기되며 판매자는 다시 경매를 진행 
			이 경우 같은 정보로 다시 글을 올릴 수 있는 장치 필요-기간만 다르게
			

5. 채팅시스템
	- 입찰 전까지는 익명으로 채팅
	- 입찰 이후에는 닉네임으로 채팅 
	- ★알림기능은 강사님께 여쭤보자


<br>

**<화면 측면>**
1. 회원 관련	
	- 회원가입 페이지
		- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간 기재하도록 한다
		- 주소 API (동 기준)

	- 마이페이지 페이지
		- 회원정보 수정 페이지
			- 프로필사진 -> 등록, 수정, 삭제
			- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간(참고용)
		- 회원정보
			- 경매후기
				- 당근마켓의 매너 상세 참고
				- 후기는 옵션으로 선택하게 한다
				- 선택 개수를 옆에 적어준다
			- 과거경매이력
				- 경매내역
					[판매자] 거래성사개수 / 중지개수 + 파기개수를 고지 
					- 경매 중
					- 경매 완료
					- 경매 중지
					- 경매 취소
				- 입찰내역
					- 입찰 중
					- 입찰 후 결제 예정 -> 결제 마감 시간 고지
					- 입찰 후 결제 완료

				
		- 탈퇴 페이지


2. 관리자 관련
	- 블랙관리 페이지
	- 허위상품관리 페이지
	- 고객센터(이메일기재 - 추후 고민)
	- 경매목록 카테고리 추가/삭제 페이지

3. 경매 관련
	1) 경매목록 페이지
		- 카테고리로 분류 (대분류)
		- 맨 처음 접속하는 경우 회원 가입 시 주소 기준으로 표시된다 (동)
		- 주소 API => 시, 구, 동 기준으로 조회하는 용도
		- 시, 구, 동 선택가능한 탭 필요
		- 검색: 카테고리 / 제목 + 내용검색
		- 경매 등록
		- [정렬 기준] 최신순 / 현재 입찰가가 낮은 순 / 현재 입찰가가 높은 순 / 
			마감시간 순 / 거래성사개수 순 (←우수 판매자 혜택)

	2) 경매상세 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 판매자 닉네임 + 프로필 => 누르면 마이페이지로 이동 OR 모달창 띄우기
		- 현재입찰가, 기간, 남은 시간
		- 경매입찰가 넣을 수 있는 입력창
		- 채팅버튼

	3) 경매등록 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 경매 시작가격, 즉시구매 가격
		- 경매 기간 == 경매 종료 날짜 및 시간 (경매는 등록 즉시 개시)	

4. 결제 관련
	1) 포인트사용: 입찰금액보다 포인트가 더 많은 경우
		- 입찰이 자동으로 진행 (잔여포인트 보여주고 결제확인 버튼있는 페이지가 필요)

	2) 포인트 충전 페이지: 입찰금액보다 포인트가 더 적은 경우
		- 충전금액?
		- API

	3) 포인트차감(출금) 페이지
		- 은행계좌 받고 버튼 누르면 완료


6. 채팅 관련 (★배우고 난 뒤 상의할 것 => 예시: 당근톡)
	- 화면관련은 미정

**Comment by Euiseon-Lee** [comment]
< 기본 전제 >

- 구매자의 포인트가 회사 측에 이동되므로

**Comment by Euiseon-Lee** [comment]
**대 전제**
- 구매자: 낙찰 시 메일로 링크를 제공하여 결제가 가능하도록 함, 회사에게 결제하도록 한다
- 판매자: 직거래가 성사된 후, 구매자가 확인버튼을 누르면 중개수수료를 제한 금액을 포인트로 이동시켜주고, 이후 출금이 가능하도록 한다
- 기본적으로 판매자가 불이익을 얻기 쉬운 구조로 되어있음

<br>


Q. [기능측면-> 3.결제시스템]에서 "포인트가 있는 상태에서는 바로 입찰 (잔여포인트 보여주고 결제확인 버튼있는 페이지가 필요) & 포인트가 없으면 포인트 충전 창으로 이동한다" 라고 기재되어 있는데 수정해야 하지 않을까?

Q. [기능측면-> 3.결제시스템]에서 "24시간 기준, 구매자가 링크를 타고 결제하지 않는 경우 거래 취소처리 => 구매자에게 불이익"이라고 되어있는데 구체적으로 어떤 불이익을 얻게 되는가?

Q. 출금 허용금액은 얼마부터인가? (챌린져스의 경우 5000원부터 출금이 가능하게 해두었다)

Q. 구매자가 직거래 후 확인버튼을 누르지 않는다면? 자동거래확정을 어떻게 할 것인가? 판매자에게도 물건을 넘겼다는 확인 버튼을 누르도록 해야 신뢰도가 올라가지 않을까?

Q. 우리의 시스템은 택배거래가 없다는 전제로 구현하는 것인가?

Q. [화면측면 -> 2. 관리자관련]에서 블랙 관리를 어떻게 할 것인가? (구체적인 방식 및 기준이 필요하다)

Q. [화면측면 -> 2. 관리자관련]에서 허위매물관리는 게시글을 이동시키는 형태로 구현하는가? 어떻게 구체적으로 관리할 것인가?

Q. [화면측면 -> 2. 관리자관련]에서 허위매물관리 시 판매자가 이의신청을 하고 싶다면 고객센터를 연결시킬 것인가?

**Comment by Gang-Eun** [comment]
- 판매자 / 구매자 불이익 파트 : 당근마켓 고객센터 -> 이용 제재 파트 참고 고려
- 불이익을 주는 기준 : 일정 기간 부정적인 평가를 누적해서 받으면 불이익 (이용 정지) 고려 
- 사용자(판매자 / 구매자)가 신고를 할 수 있는 시스템이 있으면 좋다고 생각 (고객센터 생성 고려)

**Comment by Alwayshyuk** [comment]
구매자 불이익.
 - 응찰시 결제를 뺀만큼 강력한 불이익 필요. 1회 - 사용정지 1주일, 3회 - 블랙 등
 
출금 허용
 - 동네 거래 특성상 낮은 가격의 물품이 주를 이룸. 판매 금액의 부분 출금은 제한을 두나 전체 출금은 제한을 두지 않는 방식?

거래 확인 버튼
 - 두 사용자가 만나서 거래한 후 함께 누르는 방식(중고거래 특성상 현장에서 모든 처리가 이루어져야함)  - 반응형 필수?

택배거래
 - 사용자간 대화로 비대면 거래는 가능하나 사이트측에선 별도의 기능을 제공하지 않음? 제공하더라도 개인 거래 특성상 사이트측에서 제공할 기능이 따로 없음

**Comment by Euiseon-Lee** [comment]
### 22-06-07 화 회의내용

Q. [기능측면-> 3.결제시스템]에서 "24시간 기준, 구매자가 링크를 타고 결제하지 않는 경우 거래 취소처리 => 구매자에게 불이익"이라고 되어있는데 구체적으로 어떤 불이익을 얻게 되는가?

	강은 - 	판매자 / 구매자 불이익 파트 : 당근마켓 고객센터 -> 이용 제재 파트 참고 고려
		불이익을 주는 기준 : 일정 기간 부정적인 평가를 누적해서 받으면 불이익 (이용 정지) 고려

	상혁-	구매자 불이익: 응찰시 결제를 뺀만큼 강력한 불이익 필요. 		
	        	1회 - 사용정지 1주일, 3회 - 블랙(영구정지) 등

	지연 -	상태 컬럼을 넣어서 이용제재 (로그인은 가능한데 이용 불가)

	= 이용제재 불이익 (기준은 추후 협의 필요)

<br>

Q. 판매자가 물건 판매 후 받은 포인트에 대해서) 출금 허용금액은 얼마부터인가? (챌린져스의 경우 5000원부터 출금이 가능하게 해두었다)
	
	= 동네 거래 특성상 낮은 가격의 물품이 주를 이룸. 판매 금액의 부분 출금(?????원)은 제한을 둠
 	= 전체 출금은 제한을 두지 않는 방식
	= 부분출금 기준 추후 협의 필요

<br>

Q. 구매자가 직거래 후 확인버튼을 누르지 않는다면? 자동거래확정을 어떻게 할 것인가? 판매자에게도 물건을 넘겼다는 확인 버튼을 누르도록 해야 신뢰도가 올라가지 않을까?

	<논의 사항>
	- 구매자만 거래확인 버튼을 누르는 방식
	- 판매자에게는 직거래시 반드시 확인 버튼을 눌러달라고 말해달라는 메세지 전송 (챗봇)
	- 자동거래확정 기간을 짧게하자

	<문제가 발생할 수 있는 부분>
	1. 구매자가 물건을 받지못한 상태로 거래 가능 기간이 지남
	2. 구매자가 물건을 받은 상태로 거래 확정을 누르지 않음		= 현장에서 버튼을 누를 수 밖에 없는 시스템 필요 (앱)
	
	<현재까지 나온 해결책>
	1. 이메일로 링크 발송해서 누르면 거래 완료 시 확인이 되도록 구현
	2. 반응형 웹페이지 (구현까지 시간이 소요됨, 반려)


	<합의점>
	= 구매자만 거래확인 버튼을 누르는 방식
	= 자동거래확정 기간을 짧게 => 기준 필요

<br>

Q. 우리의 시스템은 택배거래가 없다는 전제로 구현하는 것인가?

	= 당근처럼 운영
	= 사용자간 대화로 비대면 거래는 가능하나 사이트측에선 별도의 기능을 제공하지 않음
	-=제공하더라도 개인 거래 특성상 사이트측에서 제공할 기능이 따로 없음


Q. [화면측면 -> 2. 관리자관련]에서 블랙 관리를 어떻게 할 것인가? (구체적인 방식 및 기준이 필요하다)

	= 이용제재 불이익 (기준은 추후 협의 필요)

<br>

Q. [화면측면 -> 2. 관리자관련]에서 허위매물관리는 게시글을 이동시키는 형태로 구현하는가? 어떻게 구체적으로 관리할 것인가?

	- 강은: 컬럼 추가해서 정상/허위매물 표시 가능하도록 해서 관리자 측에서 관리할 수 있게
	- 지연: 상세페이지마다 신고버튼 -> 신고버튼 눌린 상세만 허위매물로 이동
	- 상혁: 10개정도 신고가 들어오면 자동 이동

	= 허위매물 신고가 일정 이상 쌓이면 경매 목록에서 이동 -> 복구 가능하도록 구현

<br>

Q. [화면측면 -> 2. 관리자관련]에서 허위매물관리 시 판매자가 이의신청을 하고 싶다면 고객센터를 연결시킬 것인가?

	- 강은: 사용자(판매자 / 구매자)가 신고를 할 수 있는 시스템이 있으면 좋다고 생각 (고객센터 생성 고려)
	- 상혁: 채팅기능에 관리자-사용자 소통기능 추가 (챗봇 고객센터)
	- 지연: 챗봇으로 처리

	= 챗봇으로 처리하자 (사용자-사용자 / 관리자-사용자로 나누어서 구현)

**Comment by Euiseon-Lee** [comment]
### 22-06-07 화 회의내용

**<파트 분배>**
1. 의선: 회원가입 / 마이페이지 / 사용자 간 채팅
2. 강은: 관리자기능 / 관리자-사용자 간 채팅
3. 지연: 경매기능
4. 상혁: 결제기능 / 경매기능

**Comment by Euiseon-Lee** [comment]
### 22-06-21 화 최종내역 업데이트

**경매 + 중고나라	=> 경매나라**

**경매나라 Overview**
	1. 지역 기반의 경매 시스템
	2. 직거래 기반으로 운영됨
	3. 참고:	당근마켓 (어플) 
		야후옥션 https://page.auctions.yahoo.co.jp/jp/auction/d1053085466
		이베이 https://www.ebay.com/itm/144564110598?hash=item21a8b14506:g:a4gAAOSwLwdiiKGr



**<기능 측면>**
1. 회원
	- 통합으로 운영 (판매자+구매자)
	- 휴대폰번호(unique)
2. 경매시스템
	- 경매형태
		1. 경매시작: 최초 입찰가 이상 입찰할 때 경매가 시작됨
		2. 즉시구매: 최고 입찰가에 도달한 경우 즉시구매가 가능 (경매는 즉시 종료)
	- 경매등록
		최대입찰/즉시구매 최고가 설정 = 1조 (14자리)
		입찰금액 기본단위 = (default)100 / 1000 / 10,000 / 100,000 / 1,000,000원 단위 
		구매자가 경매할 물품을 올리면 경매 시작이 가능해진다
			= DB에서 데이터 insert
	- 경매수정
		입찰가가 DB에 입력되면 수정불가, 그 전까지는 허용 
			= DB에서 데이터의 status 컬럼 update
	- 경매취소
		입찰한 고객이 없을 시 경매취소 가능, 불이익 없음
			= DB에서 데이터의 status 컬럼 update
	- 경매중지
		입찰이 시작된 이후 취소하는 경우
		특정 기간 동안 몇 회 이상 판매중지 시 불이익을 주는 기준이 됨
		상세페이지에서 경매중지상품으로 고지한다 
			= DB에서 데이터의 status 컬럼 update
		
	- 경매참여
		참여할땐 포인트 소모 없이 가격만 제시
	- 경매종료
		최종 입찰시에만 해당 구매자의 포인트가 소모되게 구현


3. 결제시스템
	- 포인트제도로 운영
	- 수수료 5% -> 최종 낙찰가 기준으로 적용하며 판매자 부담
	- 포인트가 있는 상태에서는 바로 입찰 (잔여포인트 보여주고 결제확인 버튼있는 페이지가 필요)
	- 포인트가 없으면 포인트 충전 창으로 이동한다
	- 포인트 충전은 API 사용
	- 포인트 (일부) 사용 시 취소 불가 (청약철회 7일)
	- 출금은 포인트 차감으로 구현 (출금했다 치고 테이블에서 제거한다) 
	- [낙찰 완료시] 확인 메일 발송 + 결제링크 (포인트 충분한지 검사 => 이 결과에 따라 이동)
	- [결제 완료시] 확인 메일 발송
	- [거래 확정 버튼] 누르면 판매자에게 포인트가 전송되는 시스템 (중개료 빼고)
	- [거래 기간] ???일 ???주 안에 거래하지 않으면 거래 취소처리 => 판매자에게 불이익 (구매자에게 포인트 돌려줘야함)
	- [결제 유효기간] 24시간 기준, 구매자가 링크를 타고 결제하지 않는 경우 거래 취소처리 => 구매자에게 불이익
			이 경우 거래는 전체 파기되며 판매자는 다시 경매를 진행 
			이 경우 같은 정보로 다시 글을 올릴 수 있는 장치 필요-기간만 다르게
			

4. 채팅시스템
	- 입찰 전까지는 익명으로 채팅
	- 입찰 이후에는 닉네임으로 채팅 
	- ★알림기능은 강사님께 여쭤보자


<hr>


**<화면 측면>**
1. 회원 관련	
	- 회원가입 페이지
		- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간 기재하도록 한다
		- 주소 API (동 기준)

	- 마이페이지 페이지
		- 회원정보 수정 페이지
			- 프로필사진 -> 등록, 수정, 삭제
			- 이름, 닉네임, 휴대폰번호, 주소, 주로 거래하는 시간
		- 회원정보
			- 경매후기
				- 당근마켓의 매너 상세 참고
				- 후기는 옵션으로 선택하게 한다
				- 선택 개수를 옆에 적어준다
			- 과거경매이력
				- 경매내역
					[판매자] 거래성사개수 / 중지개수 + 파기개수를 고지 
					- 경매 중
					- 경매 완료
					- 경매 중지
					- 경매 취소
				- 입찰내역
					- 입찰 중
				- 낙찰내역
					- 낙찰 후 결제 예정 -> 결제 마감 시간 고지
					- 낙찰 후 결제 완료
					- 낙찰 후 미결제
		- 회원 포인트 충전 / 사용 내역
			- 기간별 조회: 1개월 / 3개월 / 1년
		- 회원 포인트 현금화 내역
				
		- 탈퇴 페이지


2. 관리자 관련
	- 블랙관리 페이지
	- 허위상품관리 페이지
	- 고객센터(이메일기재 - 추후 고민)
	- 경매목록 카테고리 추가/삭제 페이지

3. 경매 관련
	1) 경매목록 페이지
		- 카테고리로 분류 (대분류)
		- 맨 처음 접속하는 경우 회원 가입 시 주소 기준으로 표시된다 (동)
		- 주소 API => 시, 구, 동 기준으로 조회하는 용도
		- 시, 구, 동 선택가능한 탭 필요
		- 검색: 카테고리 / 제목 + 내용검색
		- 경매 등록
		- [정렬 기준] 최신순 / 현재 입찰가가 낮은 순 / 현재 입찰가가 높은 순 / 
			마감시간 순 / 거래성사개수 순 (←우수 판매자 혜택)

	2) 경매상세 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 판매자 닉네임 + 프로필 => 누르면 마이페이지로 이동 OR 모달창 띄우기
		- 현재입찰가, 기간, 남은 시간
		- 경매입찰가 넣을 수 있는 입력창
		- 채팅버튼

	3) 경매등록 페이지
		- 카테고리, 제목, 내용, 사진(개수제한 필요)
		- 경매 시작가격, 즉시구매 가격
		- 경매 기간 == 경매 종료 날짜 및 시간 (경매는 등록 즉시 개시)	

4. 결제 관련
	1) 포인트사용: 입찰금액보다 포인트가 더 많은 경우
		- 입찰이 자동으로 진행 (잔여포인트 보여주고 결제확인 버튼있는 페이지가 필요)

	2) 포인트 충전 페이지: 입찰금액보다 포인트가 더 적은 경우
		- 충전금액?
		- API

	3) 포인트차감(출금) 페이지
		- 은행계좌 받고 버튼 누르면 완료


5. 채팅 관련 (★배우고 난 뒤 상의할 것 => 당근톡)
	- 화면관련은 미정
