### ISSUE TITLE
##3. 데이터 모델링 및 플로우 차트

### ISSUE THREAD

**Issue by Euiseon-Lee** [Euiseon-Lee/KH1_FINAL#3]
### 22-06-07 화 회의내용

- 기본테이블: 회원테이블, 프로필테이블, 상품테이블, 경매테이블, 게시판테이블, 첨부파일테이블
- 모델ERD: https://www.erdcloud.com/d/2mDmcrHWY3CqW4Rrp

<br>

**<USE CASE>**
- 회원가입 후 로그인을 해야지 웹페이지를 이용할 수 있도록 한다
- 모델사이트(첫 화면):	https://class101.net/login?redirect=%2F%3F

**Comment by Alwayshyuk** [comment]
카테고리 테이블 따로 관리에 대하여 의논.
 주소지 GPS 설계에 대한 의논.
 - 경매에서 당근처럼 실시간 위치로 거래 가능 여부를 판단한다면 출근, 외출 시 구매 희망 상품 입찰  불가능
 - 거래 지역을 사용자가 선택한다면 GPS 기능이 불필요
    - 구매자는 지역을 자율적으로 선택하여 경매에 참여하고(허위 응찰 위험도 상승, 부산에서 서울 상품 허위 응찰 가능) 판매 상품 등록(상품 위치 파악으로 판매자 신뢰 상승, 허위 매물 감소)과 가입 시 주소 입력(조금 억지. 맵API로 충분)에서 위치 기능을 넣어서 하는 것은 어떨지 의논

**Comment by Gang-Eun** [comment]
개인적으로 정리한 테이블 구조와 유즈 케이스 모델 (초기 단계)

erd: https://www.erdcloud.com/d/Zi59F47Y767Ljwvvx
use-case: https://app.diagrams.net/

**Comment by Euiseon-Lee** [comment]
### 22-06-10 금 회의내용
- ERD 수정 중

**Comment by Euiseon-Lee** [comment]
### 22-06-14 화 회의내용
- ERD 전체적으로 구현 완료
- 추후 논의할 내용: GPS 사용한 인근 동네 설정 / 관리자 페이지 (매출 관련 기능)
- 화면측면: 회원정보 세분화

> 			- 과거경매이력
> 				- 경매내역
> 					[판매자] 거래성사개수 / 중지개수 + 파기개수를 고지 
> 					- 경매 중
> 					- 경매 완료
> 					- 경매 중지
> 					- 경매 취소
> 				- 입찰내역
> 					- 입찰 중
> 				- 낙찰내역
> 					- 낙찰 후 결제 예정 -> 결제 마감 시간 고지
> 					- 낙찰 후 결제 완료
> 					- 낙찰 후 미결제

**Comment by Alwayshyuk** [comment]
1. 판매 상품 등록 시 GPS로 위도, 경도를 받아 등록 테이블에 저장 or 카카오 맵을 통해 주소 기재 후 위도, 경도로 계산하여 테이블에 저장
 - 거래 지역 선택과 같음.
2. 구매자 상품 리스트 페이지에서 GPS로 위도, 경도를 받고 현 위치로부터 거리를 선택하여 그 범위(원) 안의 판매 상품 구경
- ex) 위도 37.1도 경도 36.1도일 때 0.1도가 30km라면, 
사용자 반경 3km 매물 검색 - 위도 37.09~37.11 && 경도 36.09~36.11 검색 
사용자 반경 30km 매물 검색 - 위도 37~37.2 && 경도 36~36.2 검색
물론 ex일 뿐 이 식 아님, 원주율 적용해야 함

3. 판매자 정보, 제품 정보, GPS에서 위치 나오는 지역 표기 모두 위도, 경도를 지역 표기로 변환하여 표기.

상품 테이블에 위도, 경도를 추가하여 거리 계산이 가능해짐.
지역 표기도 가능해짐
전국, 전 세계 가능, 북한에서 등록하면 북한도 가능. 
정리한다고 했는데 딱히 정리할 게 없네요…. 어떠신지..

**Comment by Daybreak53** [comment]
상혁님 의견 참고해서 지역구가 아닌 좌표 반경을 기준으로 한 동네 거래 방향으로 정리해봤습니다. 
저는 매물 등록 시점의 실시간 위치가 아닌, 회원 정보에 등록하는 위치 기준입니다. 

## CASE 1 : 주소 값으로 내 동네(반경의 중심 좌표)를 설정하는 경우
### 1) 우편번호 검색 API를 통해 주소 값 얻어내기
* __카카오 우편번호 API__ 
: 사용자가 간편하게 주소 검색 및 자동 입력 가능
> 관련 문서 : https://postcode.map.daum.net/guide

### 2) 거리 측정을 위해 주소 값을 좌표 값으로 변환
* __카카오 지도 API__ 
  * 주소로 장소 표시하기
> 관련 문서 : https://apis.map.kakao.com/web/sample/addr2coord/

## CASE 2 : 현재 위치를 내 동네(반경의 중심 좌표)로 설정하는 경우
### 1) GPS를 통해 좌표 값 얻어내기
* __Geolocation API__
: 사용자가 원할 경우 웹 애플리케이션에 위치 정보를 제공할 수 있는 API로, 이를 이용해 사용자의 현재 위치 위도&경도 값(좌표)을 얻을 수 있음
> 관련 문서 : https://developer.mozilla.org/ko/docs/Web/API/Geolocation_API

### 2) 사용자들에겐 좌표 값이 아닌 주소 값으로 변환하여 노출
예) ㅁㅁ님의 현재 위치는 '서울 영등포구 선유동2로 57 이레빌딩'입니다. 이곳을 내 위치로 설정하시겠습니까?
* __카카오 지도 API__ 
  * 위도&경도 값을 통해 좌표로 주소를 얻어내기
> 관련 문서 : https://apis.map.kakao.com/web/sample/coord2addr/

참고) 위치 설정이 끝난 후, 좌표 값을 회원 테이블의 위도 컬럼, 경도 컬럼에 각각 추가. 

---

## 좌표를 통한 사용자 간 거리 측정 (구매자 <-> 판매자)
* __카카오 지도 API__ 
  *  getLength() 메서드
: 좌표 간 거리를 m(미터)단위로 반환 가능. 이를 이용해 구매자를 중심으로 특정 거리 이내의 매물만 노출 가능
> 관련 문서 : https://apis.map.kakao.com/web/documentation/#Polyline_getLength

아니면 쿼리로 계산하는 방식도 있는 것 같습니다. 특정 거리 이내 매물 리스트만 표시하려면 이 방법이 더 좋아보이네요
> 관련 문서 : https://yusang.tistory.com/48

참고) 이 경우, 동네 경매 취지에 맞게 하려면 거리 설정 옵션을 구매자에게 제공해서 거리 제한을 두어야할 것으로 보임 (예: 반경 3km / 5km / 10km 중 선택 가능. 지방은 반경 30km 옵션도 추가한다던가)

## 동네 인증
회원 테이블에 저장된 좌표 데이터와 현재 위치의 좌표를 대조하는 방식을 통해, 정기적으로 동네 인증하도록 구현하는 것도 가능해 보임
* __CASE 1) 주소 값으로 내 위치를 지정하는 경우 예시__ 
  * 최초 위치 설정 시에 동네 인증 필요O. 그 이후엔 30일이 지날 때마다 등록해둔 좌표의 반경 10km 안에 들어가서 재인증 필요
  
* __CASE 2) GPS로 내 위치를 지정하는 경우 예시__  
  * 최초 위치 설정 시엔 동네 인증 필요X. 그 이후엔 30일이 지날 때마다 등록해둔 좌표의 반경 10km 안에 들어가서 재인증 필요

**Comment by Euiseon-Lee** [comment]
**<22-06-17 금 회의 때 논의할 부분>**
1. GPS API 사용방식
2. 회원의 위치정보를 저장할 테이블

**Comment by Gang-Eun** [comment]
[관리자 기능 중간 정리]

1. 관리자 페이지 메인
	- 메인 페이지에서 차트로 보여주기
	- 사이트 순매출 (수수료) 

2. 매출 관리
	- 포인트(충전, 미사용, 사용), holding 포인트, 순매출

3. 회원 관리 
	- 회원 정보 관리 (기본 정보 수정)
	- 블랙 회원 목록, 블랙회원 등록 / 취소 (신고 횟수에 따라 자동으로 등록, 일정 기간 이후 자동으로 취소) 
	- 회원의 포인트 충전 내역 (== 결제 내역)
	- 회원의 포인트 사용 내역 (== 거래 내역) 
	- 회원의 현금화 관리 (승인 / 거절)
	- 회원 평가 항목 관리 (등록 / 수정 / 삭제)

4. 경매 관리 
	- 경매 카테고리 등록 / 수정 / 삭제 
	- 경매 게시글 관리 (공개 / 비공개 처리, 신고 횟수에 따라 자동으로 비공개 처리) 
	* 구매자-판매자 간의 채팅 내역을 관리자 페이지에서 띄우는 것이 맞는가? 

5. 챗봇 관리
	- FAQ 질문, 답변 등록 / 수정 / 삭제 
	- 사용자-관리자 1:1 채팅

**Comment by Alwayshyuk** [comment]
포인트 충전, 결제 겹침
회원 번호? 아이디를 PK로 두는게 어떤지?
결제 상품명, 결제 수량 없음. 금액으로 결제하기때문(구매 제품에 대한 충천도 해당 액수만 가져오면 됨)

**Comment by Euiseon-Lee** [comment]
### 22-06-17 금 회의내용 <br>
1. GPS API 사용방식: 상혁님 + 지연님
     - 회원 위치의 경도 및 위도를 사용해서 활용
     - ★반경 범위에 대한 추가적인 기준이 필요하다

<br>

2. 회원의 위치정보를 저장할 테이블: "회원" 테이블에서 분리시켜서 "주소" 테이블 생성
     - 회원 당 최대 2개까지 주소 등록이 가능 (GPS 사용해서 등록)
     - ★주소 초과 등록 시 백엔드에서 막을 수 있는 방법 찾기

<br>

3. "순매출액" 테이블을 만들기 위해 "포인트 사용내역" 테이블 추가

<br>

3. 신고 제도를 위한 "회원 신고 내역" 테이블과 "관리자의 회원 제재 내역"을 추가
     - 회원 신고 내역 테이블: 채팅 / 허위매물 신고 내역이 저장된다 => 구분이 필요
     - 관리자의 회원 제재 내역 테이블: 회원 신고 내역 테이블을 토대로 관리자가 최종 처리한 재제 내역에 관한 테이블, 제재 사유를 기입하여 회원들의 문의에 대비하고자 한다

<br>

5. "현금화 내역" 테이블 > 현금화 상태 컬럼 세부 내용 추가
     -  출금신청 / 출금완료 / 출금처리중
     - ★출금보류? 출금거절? 출금신청실패?    => 명칭 정리 필요

**Comment by Gang-Eun** [comment]
ERD 관련 질문 정리 

1. 회원 제재 내역 테이블의 누적 경고 횟수 컬럼의 존재 이유를 파악하지 못해서 설명을 들어야 할 것 같다. (+ 회원 제재 내역 테이블은 회원 테이블과 연결되어야 하지 않나?)

2. 포인트 충전 내역 테이블과 결제 내역 테이블의 성격이 중복되는 것 같다. 하나로 합치면 어떨까?

3. 구매자가 최종 입찰을 하여 포인트로 결제하는 테이블이 추가되어야 할 것 같다. 해당 테이블은 순매출액 테이블과 연결되어야 한다. 

4. 회원 테이블에서 블랙회원 여부 관련 컬럼이 없는데 관리자 페이지에서 블랙회원으로 바로 등록할 때 누적 경고횟수를 바로 10으로 설정?

5. 경매 물품 테이블에 게시글 공개 설정 여부 컬럼을 추가하는 것은 어떨까?

**Comment by Euiseon-Lee** [comment]
### 22-06-21 화 문의 및 회의 내용

<br>

**<문의 내용>** 
1. 강도테스트
	- 5초에 한 번씩 최대 500명이 들어옴 => 특정 기능에 부하가 얼마나 걸리는지 테스트

2. 22-06-24 금요일부터 파이널 프로젝트 시작할 확률은 2% (매우 희박)
	- 그럼에도 전원 다 출석하여 회의 진행하기로 함

3. 기능이 겹치는 것이 아니라면 팀원 간 비동기 사용 방식을 통일할 필요는 없다

4. 반경 기능에 대한 기준을 설정할 것
	- 강사님: 인접 구에 대한 정보를 추출하여 면적을 누적 계산하는 방식으로 알려주심
	- 지연님: 경매물품 간 거리 계산을 통해 반경 내에 해당하는 경매물품들을 목록에 띄워주자
	- 상혁님: 경도/위도를 반경을 반영해서 추출한 뒤 범위를 설정하자

5. 주소 2개 이상 등록 못하게 백엔드에서 처리하는 방법
	- 등록 전에 count로 조회하여 count > 2일 때에는 수정이 되도록 구현할 수 있다

6. 신고테이블 분할 => OK


<hr>

**<추가적으로 생각해야하는 부분>**
1. GPS 사용방식
	- 당근마켓의 반경설정 기준 강화하기
	- 위도 및 경도 기준으로 계산하는 식을 구체화하기

2. 경매 목록에서 시간 카운트 다운을 실시간으로 할 것인가? 부하가 와서 하지 않는다면 구체적인 프론트 구현 방향

3. 거래 완료 후 평가를 어떤 페이지에서 진행할 것인가
	- 후보: 마이페이지 > 낙찰내역 > 결제완료 / 회원 간 채팅방 / 해당 경매물품 상세페이지

4. 입찰 마감시간이 1시간 내로 줄어들면 입찰가를 갱신하지 않게 되는데 어떤 방식으로 이를 표현할 것인가 (프론트)

5. 경매 상세페이지 > 경매인 정보를 보여줄 때 평가 지수를 보다 직관적으로 보여줄 수 있는 방법?
	- 총 평가 개수 / 긍정 평가 개수 / 부정 평가 개수를 그대로 보여주는 것으로 이야기했으나 더 좋은 방법 강구할 필요

6. 직관적인 UI -> 보다 사용자 친화적인 부분 고려해보기

7. 각자 구현할 페이지를 지연님 피그마 파일에 기반하여 구상해보기


<hr>

**<다음 회의 시 고려할 부분: 강은님 질문>**

1. ERD 관련 질문 정리

2. 회원 제재 내역 테이블의 누적 경고 횟수 컬럼의 존재 이유를 파악하지 못해서 설명을 들어야 할 것 같다. (+ 회원 제재 내역 테이블은 회원 테이블과 연결되어야 하지 않나?)

3. 포인트 충전 내역 테이블과 결제 내역 테이블의 성격이 중복되는 것 같다. 하나로 합치면 어떨까?

4. 구매자가 최종 입찰을 하여 포인트로 결제하는 테이블이 추가되어야 할 것 같다. 해당 테이블은 순매출액 테이블과 연결되어야 한다.

5. 회원 테이블에서 블랙회원 여부 관련 컬럼이 없는데 관리자 페이지에서 블랙회원으로 바로 등록할 때 누적 경고횟수를 바로 10으로 설정?

6. 경매 물품 테이블에 게시글 공개 설정 여부 컬럼을 추가하는 것은 어떨까?
